services:
  postgres:
    container_name: amigo-database
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: amigo-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/amigo-database
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  frontend:
    container_name: amigo-frontend
    build: /Users/lulu/UBB/ANII/Semestrul4/amigo-fe
    ports:
      - "3000:80"

volumes:
    postgres-data: